### ISSUE TITLE
Retained File Count Limit should default to null not 31

### ISSUE THREAD

**Issue by CedricYao** [serilog/serilog-sinks-rollingfile#2]
I believe that any logging framework should be overly pessimistic rather than optimistic. Since the last thing anyone wants to find is Serilog has deleted that log file you needed to troubleshoot from over a month ago.

**Comment by nblumhardt** [comment]
Thanks for the feedback Cedric! Changing the default right now, even for 2.0, could cause some nasty surprises for people. While keeping the logs is important, ensuring the logs don't exhaust disk space and thus potentially bring down a production app is also a concern.
