### ISSUE TITLE
New feature shared: true locks file when writing

### ISSUE THREAD

**Issue by MartinGian** [serilog/serilog-sinks-rollingfile#20]
Hi,

Great job with this new feature! I have a problem now.. sometimes when I try to access the log file and read it with notepad, shows me an error that says the file is locked by another process.

This behaviour is because the new feature? There is a way to avoid it?

Thanks you!

**Comment by nblumhardt** [comment]
Thanks for the report Martin. The `shared` implementation is missing `FileShare.Read`. I've PR'd the change upstream in _Serilog.Sinks.File_; it's a very minimal change so I'll push it through to publish a dev package including it shortly.

**Comment by nblumhardt** [comment]
Hi again - package _Serilog.Sinks.File_ version _3.0.1-dev-00741_ is now on NuGet. If you update (e.g. via `Update-Package Serilog.Sinks.File -Pre`) is the issue resolved?

Thanks!

**Comment by MartinGian** [comment]
Hi Nicholas, thanks you. Is working fine now.
