### ISSUE TITLE
Current log file locked on Azure App Service

### ISSUE THREAD

**Issue by pbering** [serilog/serilog-sinks-rollingfile#28]
Hi, the current log file is locked until I stop the app service, is there any way to enable that I can either download the current log through ftp or by using "Clould Explorer" in Visual Studio without stopping the app first? I've tried setting the "shared: True" option but I get platform not supported (both locally and on Azure)

**Comment by nblumhardt** [comment]
Thanks for getting in touch. Are you using version 3.0.1 of the package?

The file should be shared as readable by default: https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/Sinks/File/FileSink.cs#L64 - not sure what on Azure App Service might affect this. Is there any other information you can think of that might offer some clues?

**Comment by pbering** [comment]
Hi, sorry for the missing info...  I'm on ASP.NET Core 1.0.1 and using the RollingFile sink `"Serilog.Sinks.RollingFile": "3.0.1"`

**Comment by nblumhardt** [comment]
Thank you, that's interesting. I don't have too many ideas, unfortunately - hopefully someone else spotting this ticket might know what's likely to be going on....

**Comment by m-mains** [comment]
I'm experiencing the same issue, running ASP.Net 4.6, but Serilog.Sinks.RollingFile 3.0.0.

I'm curious to know if you're experiencing this with the static logger or with a created instance? I'm working on an application and currently using only the static logger. Logging is only partially integrated currently so I hadn't put much work into it and was starting off with the static logger.

**Comment by pbering** [comment]
I followed the instructions from https://github.com/serilog/serilog-extensions-logging/blob/dev/README.md so I assume that it's being held statically in the .NET Core IoC cotnainer.

**Comment by nblumhardt** [comment]
@pbering even if so, log files can usually be copied/viewed while they're in use (Just triple-checked this on my development machine :-)). Do other files held open by the app - `File.Open(... FileShare.Read, ...)` - get locked also?

**Comment by pbering** [comment]
@nblumhardt agree, must be a Azure App Service thing, I will try to isolate what is going on.

**Comment by m-mains** [comment]
For the time being I've found somewhat of a workaround. You can't copy the file directly, but viewing the scm region for your site (App Service Editor), you should be able to view the current log file.

e.g. yoursitename.scm.azurewebsites.net/dev

**Comment by pbering** [comment]
@mattm91 thanks for the tip! My logs files are located "/LogFiles/app" and it seems I can't access them through the App Service Editor. But I can get to them and view them without stopping the site, through the DebugConsole in KUDO.

**Comment by nblumhardt** [comment]
If the files can be viewed with other tools on the platform, it sounds likely that this one isn't a Serilog issue. Is that consistent with what you're thinking, @pbering @mattm91?

**Comment by m-mains** [comment]
That's what I think. This can't be a Serilog issue. This is either
something with Kudu integrating with Azure or an entirely Azure thing,
related to Kudu having exclusive access to certain files.

**Comment by pbering** [comment]
@nblumhardt I agree that this is not a Serilog issue and I'll close it - thank you for your input!

**Comment by yosigolan** [comment]
Hey. i know this issue is closed but i am experiencing the same problem with .net core 2. maybe someone knows how to solve it?

Thanks Yosi

**Comment by stt106** [comment]
@yosigolan  Debug Console in KUDO workaround still works. Go to https://{yoursite}.scm.azurewebsites.net

**Comment by yosigolan** [comment]
Hey @stt106 , thanks for the answer but i am not sure how it solved the problem. you mean open the log file using the kudo console? with which app? just display it?
what if i want to use a software that open the file in tail mode?

thanks Yosi

**Comment by marcasmar94** [comment]
Any updates for this?  Experiencing the same problem with .net core 2.1

**Comment by antdimot** [comment]
Hi, I have the same problem with .net core 2.1

**Comment by techaimail** [comment]
I have the same problem using Serilog Rolling Nuget Package version 3.0.3 over ASP .NET Core 2.2.4 runing on Azure App Service and this is the code to create the logger (the file that is created is always locked, but if I create anothe one with C# setting FileShare.Read is not locked)

new LoggerConfiguration().WriteTo.RollingFile(logFilePath, shared:true, retainedFileCountLimit:31).CreateLogger()
