### ISSUE TITLE
Log folder/file(s) not being created on Azure Web Service

### ISSUE THREAD

**Issue by CTDevRic** [serilog/serilog-sinks-rollingfile#34]
We have an Azure Web Service running an instance of IdentityServer3 and would like to do some logging. All works fine when running local, but when published to Azure through Visual Studio, the described folder "logs" is not created, and neither are the log file(s).

Any ideas on what might be in the way and keeping these items from being created?

Not using anything fancy...just the real basic setup:

```
Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.LiterateConsole()
                .WriteTo.RollingFile(@"C:\logs\devs3server-{Date}.txt")
                .CreateLogger();
```

and `Log.Information("Started logging.");`

**Comment by nblumhardt** [comment]
Hi Ric,

I'd guess it's more than likely the account under which the web service is running doesn't have permission to write to C:\logs.

Cheers,
Nick

**Comment by CTDevRic** [comment]
Nick,

Thanks for that. I adjusted the path to be `WriteTo.RollingFile("~\\logs\\devs3server-{Date}.txt")` to get it at the root of the project, where, presumably, I do have permission to write. Still no joy.

Any other ideas?

Cheers,
Ric

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I don't think `~` will work in paths unless `Server.MapPath()` is applied - that may be one thing to check out.

[SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics#selflog) will provide some clues if all else fails.

Cheers,
Nick

**Comment by CTDevRic** [comment]
Nick,

Thanks for the info. You put me on the correct path (no pun intended). My logger is configured below, and all is working as expected.

Thanks for the help!

```
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.LiterateConsole()
    .WriteTo.RollingFile(System.Web.HttpContext.Current.Server.MapPath(@"~\logs\s3server-{Date}.txt"))
    .CreateLogger();
```

**Comment by nblumhardt** [comment]
Great, glad to hear you were able to get it working 👍
