### ISSUE TITLE
Logfile should be recreated if it got deleted while the server is running.

### ISSUE THREAD

**Issue by derFunk** [serilog/serilog-sinks-rollingfile#36]
That's what I'm currently experiencing.

When deleting the logfile while the server is still running, I'm expecting the running server to recreate the log file.

Currently I'd have to restart the server (ouch) just to get the logfile back again.

**Comment by derFunk** [comment]
Additionally: When emptying the file, instead of deleting it (by e.g. doint `echo 1 > logfile.log`) SeriLog also does not write to it anymore, although the filesize is now 1B.

**Comment by nblumhardt** [comment]
Hey Andreas, thanks for the note. I think this would be a reasonable improvement to make, but just to clarify - is deletion of the log file on the server a regular occurrence in your infrastructure, or was this just a one-off? (I.e. are you using a log collector that does this automatically?)

**Comment by jchannon** [comment]
I just hit this. I deleted the file and expected it to be recreated. It's not something that I would hope would happen in production but nevertheless, seems a large hole

**Comment by JoeStead** [comment]
Had a quick look at the sink, seems to be an issue with[ serilog/serilog-sinks-file](https://github.com/serilog/serilog-sinks-file) which is a dependency of this project. Perhaps the issue should be raised there?

**Comment by nblumhardt** [comment]
As it's unlikely at present that we'll enable the functionality in _RollingFile_, let's move discussion over to: https://github.com/serilog/serilog-sinks-file/issues/96

Thanks for all the input on this :+1:
