### ISSUE TITLE
Implement multi-process log file sharing on .NET Core

### ISSUE THREAD

**Issue by derFunk** [serilog/serilog-sinks-rollingfile#37]
There is a parameter `shared` when creating a RollingFile sink.
But currently it's throwing a NotSupportedException when set to `true`.
See also https://github.com/serilog/serilog-sinks-rollingfile/blob/1c88099281b12ca2c0e9434e351c86298f92e23a/src/Serilog.Sinks.RollingFile/Sinks/RollingFile/RollingFileSink.cs#L157-L163

What's the status here?
 - Is it working to write to one file from multiple processes even if this shared parameter is set to false?
 - If not, will this be implemented?

**Comment by nblumhardt** [comment]
Hi @derFunk - `shared` works on .NET Framework, but the APIs used are not (yet?) available on .NET Core. My guess is you're receiving `NotSupportedException` on core - is that right? Thanks!

**Comment by derFunk** [comment]
Yes, I'm on .NET Core.
Thanks for clarification!

**Comment by nblumhardt** [comment]
Re-titled to cover the .NET Core aspect. Not sure what the appropriate cross-platform way to implement this is (close/reopen is hideously slow). Any ideas out there?

**Comment by skomis-mm** [comment]
@nblumhardt , what do you think about serializing writing/flushing with `Mutex`es?

**Comment by nblumhardt** [comment]
Ooh interesting - I didn't think `Mutex` was on .NET Core. Yes, that's the top contender then :-) 👍

**Comment by nblumhardt** [comment]
I've PR'd a basic implementation in https://github.com/serilog/serilog-sinks-file/issues/27. Once we're happy with it, we can incorporate it downstream here.

**Comment by nblumhardt** [comment]
PR in #40.

**Comment by nblumhardt** [comment]
Hi all - this is now in the [pre-release NuGet package](https://www.nuget.org/packages/Serilog.Sinks.RollingFile/3.3.0-dev-00758), any feedback welcomed!
