### ISSUE TITLE
Ability to get hold of log filename?

### ISSUE THREAD

**Issue by MagnusJohansson** [serilog/serilog-sinks-rollingfile#39]
In my app, I want to be able to either open the log file from the UI and/or send the log file automatically to a backend server for further analysis.
However, it seems impossible to get hold of the current log filename.
Am I missing something here?

**Comment by nblumhardt** [comment]
Hi Magnus, thanks for the note. No, you're not missing any built-in functionality. Given a directory of files though, would choosing the latest based on last-write-time give you what you need?

For displaying logs in-app, for deskopt apps it can work quite well to implement `ILogEventSink` and put the events in a size-limited in-memory queue that can be read and displayed.

Regarding shipping to a back-end - is there a sink package available for the back-end you're using? Most of the time there's a way to skip the log file altogether in these cases.

HTH!

**Comment by nblumhardt** [comment]
Would #26 - fixed filename with numbered archive files - cover this?

**Comment by j2jensen** [comment]
I got here while googling for the same purpose as Magnus. I think #26 would be a good solution for this, but in the meantime I can try a workaround to detect the highest filename in the folder that matches the naming pattern.

One question I have, though, is whether it's likely to cause any issues if my web app is feeding the log file into a download while Serilog is appending messages to that file? I haven't really had to dig into concurrent file access issues like this, though I suspect that you probably have, @nblumhardt . Can you speak to this at all?

**Comment by nblumhardt** [comment]
Hi @j2jensen - a short snippet of code based on the `_filenameMatcher` and `DirectorySearchPattern` here should do it: https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/src/Serilog.Sinks.RollingFile/Sinks/RollingFile/TemplatedPathRoller.cs#L63 ... would whip this up now for you, but stuck for time this afternoon. Hoping we can get this into a Gist or similar to help with this case. Cheers!
