### ISSUE TITLE
[Feature] Possibility to add Specifiers for filenames

### ISSUE THREAD

**Issue by sschutten** [serilog/serilog-sinks-rollingfile#43]
Would like to add Specifiers to split log files by custom defined rules.
For example on log level, context or other properties.

**Comment by sschutten** [comment]
I went ahead and created an extension to the RollingFileSink named [ContextRollingFileSink](https://github.com/sschutten/serilog-sinks-contextrollingfile) that does exactly this.

**Comment by nblumhardt** [comment]
Great! Glad you were able to make this work 👍
