### ISSUE TITLE
Ability to disable rolling log

### ISSUE THREAD

**Issue by josephwoodward** [serilog/serilog-sinks-rollingfile#44]
What are people's thoughts on adding an optional parameter to the `RollingFile` method to disable the rolling file log?

In this instance, as I'm setting up rolling file logging via an appsettings, using the following configuration:

```json
  "Serilog": {
    "WriteTo": [
      {
        "Name": "RollingFile",
        "Args": {
          "pathFormat": "log-{Date}.txt",
          "retainedFileCountLimit": 3,
          "shared": true
        }
      }
    ]
  }
```

It would be really handy to disable rolling file logging in development in my appsettings.development.json file.

I'm more than happy to contribute this change if you feel it's one that would be valuable.

**Comment by nblumhardt** [comment]
Hi Joseph, thanks for the note!

Why not just add the rolling file configuration section into a production JSON config file?

Cheers,
Nick

**Comment by josephwoodward** [comment]
Do you mean remove the configuration from appsettings.development.json and add it into appsettings.json?

I'm configuring the rolling file by calling `.ReadFrom.Configuration(configuration)`, and I presume that it will throw some kind of exception if I remove the Serilog config settings from the development JSON config file? (though I'm unable to confirm this right now).

**Comment by nblumhardt** [comment]
Hi Joseph, you should be able to add a new JSON config file using the production environment name, e.g. `appsettings.Production.json`, and add the rolling file configuration in there.

`ReadFrom.Configuration()` shouldn't throw if the config is empty (I also need to verify), but in any case including an empty `"Serilog":{}` node in appsettings.json would take care of it.

Hope this helps!

**Comment by josephwoodward** [comment]
Oh great, perfect - an empty `"Serilog":{}` node will do the job, didn't think of that. I'll add an empty config tomorrow when I'm at work and see what it does then report back.

**Comment by nblumhardt** [comment]
Looks like this one is good to close, let me know if you need any more info here. Cheers!
