### ISSUE TITLE
Restrict to level

### ISSUE THREAD

**Issue by josephwoodward** [serilog/serilog-sinks-rollingfile#45]
Hi,

What's the best approach to restricting a log to a certain level? I see `RollingFile` has a `restrictToMinimumLevel` parameter, but if I wish to restrict the log data to only errors then I can't see this being an option. I recall there being a filter API which seems like it would be the next best thing.

Alternatively could you see much value in having a `restrictToLevel` property available on the method?

**Comment by nblumhardt** [comment]
Hi Joseph, this should work for you:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Logger(lc => lc
        .Filter.ByIncludingOnly(evt => evt.Level == LogEventLevel.Error)
        .WriteTo.RollingFile("errors.txt"))
    .WriteTo.Logger(lc => lc
        .Filter.ByIncludingOnly(evt => evt.Level == LogEventLevel.Warning)
        .WriteTo.RollingFile("warnings.txt"))
    .CreateLogger();
```

How's that fit? Cheers!

**Comment by josephwoodward** [comment]
Nice, that should do it! On a side note, do you have any up for grabs issues that are suitable for someone new to Serilog? I'd love to contribute if I could, Serilog is an awesome library!

**Comment by nblumhardt** [comment]
Great, thanks for the interest!

There are a lot of repositories spread around the organisation with a few up-for-grabs item in there.

If you're interested in Linux _and_ Win 10, I think https://github.com/serilog/serilog-sinks-literate/issues/9 would be a fun one?
