### ISSUE TITLE
Readme.md should mention new options

### ISSUE THREAD

**Issue by ltd65** [serilog/serilog-sinks-rollingfile#46]
The readme does not mention that there are now new pattern for the date specification {Hour} and {HalfHour}. Also it is not clear if the filecountlimit will stay at default 31 (my expectation) or if they are different. Like 24 for Hour and 48 for HalfHour to allways cover a day.

**Comment by merbla** [comment]
@ltd65 feel free to drop a PR with the changes you are thinking about to the README.

**Comment by ltd65** [comment]
Will look at it. Might take a little bit. Base reason is that I never before did contribute, so I will have to lookup how to do it correctly. (Also not that fit on git so far due to only using SVN at work)

**Comment by merbla** [comment]
@ltd65 it would be great to have your contribution.  

For a README change you could [fork](https://guides.github.com/activities/forking/) the repo and make the edits in the browser then create a [PR](https://guides.github.com/activities/forking/).

You may not need to know Git in detail for this commit. 😃

**Comment by ltd65** [comment]
PR created.
