### ISSUE TITLE
Multiple files being created before roll algorithm is invoked

### ISSUE THREAD

**Issue by stephenpatten** [serilog/serilog-sinks-rollingfile#49]
Hello,

Given the following setup in an ASP.Net website startup:

    var builder = new ContainerBuilder();
    builder.Register(c => ConfigureLogger()).As<ILogger>();
    builder.Build();

        public static ILogger ConfigureLogger()
        {
            var level = new LoggingLevelSwitch(LogEventLevel.Debug);
            var filePath = ConfigurationManager.AppSettings["serilog:Log:FilePath"] +
                $"RequirementsWS_{Environment.MachineName}_";
            return Log.Logger = new LoggerConfiguration()
                .MinimumLevel.ControlledBy(level)
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .Enrich.WithThreadId()
                .WriteTo.Seq(ConfigurationManager.AppSettings["serilog:write-to:Seq.serverUrl"],
                    apiKey: ConfigurationManager.AppSettings["serilog:write-to:Seq.apiKey"],
                    controlLevelSwitch: level,
                    compact: true)
                .WriteTo.RollingFile(filePath + "{Date}.log",
                    outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message}{NewLine}{Exception}")
                .CreateLogger();
        }

I'm wondering what might be causing multiple files to be generated as shown in the attached screenshot.

Thank you,
Stephen

![snap404](https://cloud.githubusercontent.com/assets/354728/25146178/ccc1d814-2427-11e7-8b1c-d2d6f78ef2b0.png)

  <package id="Serilog.Enrichers.Thread" version="3.0.0" targetFramework="net452" />
  <package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net451" />
  <package id="Serilog.Sinks.Console" version="2.1.0" targetFramework="net451" />
  <package id="Serilog.Sinks.File" version="3.2.0" targetFramework="net452" />
  <package id="Serilog.Sinks.Literate" version="2.1.0" targetFramework="net452" />
  <package id="Serilog.Sinks.PeriodicBatching" version="2.1.0" targetFramework="net452" />
  <package id="Serilog.Sinks.RollingFile" version="3.3.0" targetFramework="net452" />
  <package id="Serilog.Sinks.Seq" version="3.2.0" targetFramework="net452" />

**Comment by skomis-mm** [comment]
Ensure you register a single instance of `ILogger`:
```csharp
builder.Register(c => ConfigureLogger()).As<ILogger>().SingleInstance();
```
otherwise it will be transient by default

**Comment by jaslam94** [comment]
> Ensure you register a single instance of `ILogger`:
> 
> ```cs
> builder.Register(c => ConfigureLogger()).As<ILogger>().SingleInstance();
> ```
> 
> otherwise it will be transient by default

What would be its equivalent in MVC5?
