### ISSUE TITLE
Use properties in path format

### ISSUE THREAD

**Issue by JanEggers** [serilog/serilog-sinks-rollingfile#50]
currently im able to split my logiles by static filters like:

 Log.Logger = logger
                .WriteTo.Async( a => a.Logger( lc => lc
                    .Filter.ByIncludingOnly( e => HasScope( e, "SomeScope" ) )
                    .WriteTo.Async( a2 => a2.RollingFile( $"{directory}{{Date}}_SomeScope.log" ) ) ) )
                .CreateLogger();

what i would really like to do is something like:

Log.Logger = logger.WriteTo.Async( a2 => a2.RollingFile( $"{directory}{{Date}}_{{Scope}}.log", outputTemplate: template ) )
                .CreateLogger();

meaning all properties in a logevent should be usable to modify the pathFormat and so the resulting path.

**Comment by nblumhardt** [comment]
Hi Jan, thanks for the note, it's a reasonable feature to consider.

As you can probably tell from your experience with the sink so far, I'm keen to try keeping the rolling file sink itself as simple as possible, baking in these things only at the last possible moment.

One option that would achieve what you're after, but work outside the rolling file sink, might be to implement an API like:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Map("Scope", (lc, scope) => lc
        .WriteTo.RollingFile( $"{directory}{{Date}}_{scope}.log", outputTemplate: template))
    .CreateLogger();
```

`Map()` would accept the name of a scalar-valued property, and internally maintain a dictionary of value &rarr; logger pairs to which it would forward events based on the value of the property.

Making this work efficiently might require some kind of "garbage collection" to evict sub-loggers not used in some amount of time, but the same would be required to manage file handles within the rolling file sink, were we to implement it directly there.

Thoughts?

Cheers!

**Comment by JanEggers** [comment]
api is looking good. i wasnt shure in the first place if i should put the issue in here or in the serilog main repository

**Comment by JanEggers** [comment]
@nblumhardt i didnt find a roadmap or future milestones can you give me a rough eta when this will be implemented? i could provide a pr but i fear the resulting code might not have the quality required for this library...

**Comment by nblumhardt** [comment]
Hi Jan, thanks for the bump.

There's no timeline for this - I'd love to have a shot at it but I'm not sure when I'll have the opportunity.

Shipping this as a separate package _Serilog.Sinks.Map_ could be a decent option that would get the ball rolling quicker. Marking it as "up for grabs".

CC @serilog/reviewers-core

**Comment by nblumhardt** [comment]
Hi again- I've sketched up a basic implementation of `WriteTo.Map()` at:

https://gist.github.com/nblumhardt/e9477bf4c3e2acf13ae4227323cd0407

Thoughts?

**Comment by nblumhardt** [comment]
Initial version now on GitHub/NuGet: https://github.com/serilog/serilog-sinks-map

**Comment by JanEggers** [comment]
nice for my usecase it needed a custom key selector to access the scope but with that it works like intended.

**Comment by khellang** [comment]
Woah, that's some crazy use of C# 7 right there;

```csharp
if (le.Properties.TryGetValue(keyPropertyName, out var v) && v is ScalarValue sv && sv.Value is TKey key)
```

❤️

**Comment by JanEggers** [comment]
i love it too all nice in one line

**Comment by nblumhardt** [comment]
My favourite C# 7 feature without doubt :-)

**Comment by JanEggers** [comment]
@nblumhardt can u please open the issue again until it is baked into an official package? just for me to keep track of it.

**Comment by nblumhardt** [comment]
Hi Jan -

> Initial version now on GitHub/NuGet: https://github.com/serilog/serilog-sinks-map

This is it :-)

If you hit issues/gaps, it'd be great to have feedback. Thanks!

**Comment by JanEggers** [comment]
i now use the package works great like before.

just out of curiosity why not change key selection to something like:

```
            if ( property is ScalarValue sv )
            {
                return sv.Value.ToString();
            }

            if ( property is SequenceValue seq )
            {
                return string.Join( ".", seq.Elements.Select( SelectLogKey ) );
            }
```

that way scope property would work out of the box

**Comment by nblumhardt** [comment]
Thanks for the note. Right now I guess the goal is to provide something flexible/general - other use cases might need to treat sequences differently.

**Comment by KEMBL** [comment]
@nblumhardt hello, it seems a typo in the example  https://github.com/serilog/serilog-sinks-map  
{{Date}}  produces log-Alice-{20170606}.txt

BTW, why not allow such construction too:

`
string pathTemplate = "logfile-{Date}-{Suffix}.log";
...
               .WriteTo.Map("Suffix", (name, wt) => wt.RollingFile(pathTemplate))
               .Enrich.WithProperty("Suffix", "simple")`

or even

`logger.ForContext("Suffix", "othersuffix");`
