### ISSUE TITLE
RestricTo Level configuration in appSettings.json

### ISSUE THREAD

**Issue by anicoll** [serilog/serilog-sinks-rollingfile#51]
Hi I am looking all over for a way to configure multiple rolling files for specific log levels such as `randomName-{Level}-{Date}.log`

I cant seem to find anything only this issue https://github.com/serilog/serilog-sinks-rollingfile/issues/45
which defines the solution as a hard-coded one. I want specific level logging per each file.

Is this available and if not would it not make sense to add this?

**Comment by nblumhardt** [comment]
Hi @anicoll - no, adding multiple individual rolling file loggers and using `restrictedToMinimumLevel` in the configuration is the only current option.

https://github.com/serilog/serilog-sinks-rollingfile/issues/50#issuecomment-299048378 might also apply to this case, though the mentioned `WriteTo.Map()` doesn't exist yet.

HTH,
Nick

**Comment by nblumhardt** [comment]
Hi! This is now available, via `Serilog.Sinks.Map`:

https://github.com/serilog/serilog-sinks-map

Example:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Map(le => le.Level, (level, wt) => wt.RollingFile($"./logs/log-{level}-{{Date}}.txt"))
    .CreateLogger();
```
