### ISSUE TITLE
One log file per month

### ISSUE THREAD

**Issue by zee1593** [serilog/serilog-sinks-rollingfile#52]
We have several scripts that run once daily. It would be handy to have a "Month" specifier so that there is exactly one log file per month.
Thank you for your time.

**Comment by nblumhardt** [comment]
Thanks for the note! This sounds like a low-impact enhancement. If anyone has the opportunity, a PR would be welcome for this.

**Comment by pardahlman** [comment]
I think it would makes sense to make this configurable, e.g. the default is rolling file once per day, but it might as well be every second day, once a week etc.

The only problem that I see is that if the file is configured to roll every half a day (12h), the file naming convention needs to be updated to include more detailed date part. That could probably be solved by supporting formatting of the `Date` placeholder (`{Date:yyyy-MM-dd-HHmm}`).

What do you think?

**Comment by nblumhardt** [comment]
I've just started work on merging the current rolling file functionality directly into _Serilog.Sinks.File_, and per-month rolling is one of the options I'm aiming to open up.

Custom formatting (and in fact the whole `{Date}` path templating mechanism) requires some pretty sophisticated parsing logic to find matching files and order them correctly for file retention purposes. I think the updated sink is going to be more prescriptive about how filenames are formed, but offer year, month, day, hour and minute rolling options.

I'll post a PR as soon as I have something working :-)

**Comment by nblumhardt** [comment]
I've implemented this in https://github.com/serilog/serilog-sinks-file/pull/35

**Comment by zee1593** [comment]
Thank you.  This feature is going to be used a lot!
