### ISSUE TITLE
UdpClient is disposed before send completes (UdpClientTransport)

### ISSUE THREAD

**Issue by ervinche** [serilog/serilog-sinks-rollingfile#53]
Hello,

We are having some trouble using the library because in some scenarios the UdpClient gets disposed before the message sending completes.
In the UdpClientTransport class the Send method creates the udpClient instance wrapped in the using directive. The returned Task is not executed and completed instantly resulting in disposing the udpClient instance which is still needed.
The actual result is getting an exception with the message: 'Cannot access a disposed object'.
.......
StackTrace
at System.Net.Sockets.Socket.EndSendTo(IAsyncResult asyncResult)
   at System.Net.Sockets.UdpClient.EndSend(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

Could you please take a look into this issue,

Thank you

**Comment by nblumhardt** [comment]
Hi! I think this might be in the wrong repository; this one is for the Serilog rolling file sink. When you re-raise this one, could you also please include a code snippet showing your configuration code? Thanks!

**Comment by ervinche** [comment]
Sorry, for the wrong repository, re-raised it at https://github.com/whir1/serilog-sinks-graylog/issues/10
