### ISSUE TITLE
Is it possible to have a logfile per day for a process that runs longer than a day?

### ISSUE THREAD

**Issue by SharpNoiZy** [serilog/serilog-sinks-rollingfile#55]
I have the issue that I have an application that runs days or weeks until it get's restarted.
And what happens is that I get a logfile with the date the application was started in the name.
But also logs from the following days go to the same logfile until I restart the application, than the new date log file is created.

Is it possible that this sink, checks that?

**Comment by nblumhardt** [comment]
Hi - yes, that's what this sink does. Are you seeing different behavior? Thanks!

**Comment by nblumhardt** [comment]
Hi @SharpNoiZy - I'm not 100% clear on what the current and expected behaviors are from the description you've given; I'll close this as there hasn't been any activity, but please feel free to open a new ticket with some more information if you need help. Cheers!
