### ISSUE TITLE
Sync structured log file to DB

### ISSUE THREAD

**Issue by xaviergxf** [serilog/serilog-sinks-rollingfile#56]
Hi,

   I was thinking about using this sync as fallback log with json formatter to create a structured log file(One log file per day). The ultimate goal is to try to log first into the database and if its unnacessible log into the fallback log: serilog-sinks-rollingfile. On the next day i would like to put all this log into the DB and delete the past log file. Are there any tips on how to do this? How can i know which is the current log file? How about multi-processes reading/writing into the log file?

Thanks!

**Comment by nblumhardt** [comment]
Hi Xavier,

There's no built-in support for this with the MSSqlServer sink currently; a few sinks (Seq and Elasticsearch, IIRC), implement a "durable" mode that behaves the way you describe. The code in them shows how rolling file sets are managed - see, e.g. https://github.com/serilog/serilog-sinks-seq/tree/dev/src/Serilog.Sinks.Seq/Sinks/Seq/Durable.

If you decide to code something up, `Serilog.Formatting.Compact.Reader` is your friend in this endeavour :-)

Not much I can add right now, but please feel free to get in touch if you hit any blockers.
