### ISSUE TITLE
Allow 2-digit years in filenames

### ISSUE THREAD

**Issue by Atenista** [serilog/serilog-sinks-rollingfile#57]
We have a lot of legacy code whose log filenames have only 2 digits for the year (i.e. yyMMdd). We're adding new components written with .NET Core and need their log filenames to use the same; please consider adding the option to make that possible...

**Comment by nblumhardt** [comment]
Hi! Thanks for the note!

This could be done, but just wondering - the turnaround time will still not be great if you need this now. May be a better result if you just update to emit all files with the new names?

Nick
