### ISSUE TITLE
Rolling file until size limit?

### ISSUE THREAD

**Issue by aloh86** [serilog/serilog-sinks-rollingfile#58]
Hi, the doc says that it will insert {Date} into the file name by default if not provided, causing the rolling file to produce a log per day.

This is my first time using a rolling file, and I'm starting to think I misunderstood the concept. I thought the purpose of a rolling file was that if you hit a memory limit (say, 512000 bytes), then it will create a new file. If that file hits the limit, another new file is created until the maximum file limit is reached, which then wraps back around to overwrite the very first file (kind of like a snake eating its own tail).

It seems the way serilog-sinks-rollingfile works is that each day you have one log file, and with that one log file you can set a limit. If it hits the limit, it will no longer write to the file, and the user must wait until the next day for anything to be written (to a new file). Is this correct?

Is there a way I can make it work like the former scenario?

**Comment by aloh86** [comment]
doh! I totally missed the first line in docs. 

**"Writes Serilog events to a set of text files, one per day."**

**Comment by nblumhardt** [comment]
Hi Alex, thanks for getting in touch.

There turn out to be a _lot_ of different ways to configure rolling log files - the default Serilog rolling file sink is set up with one set of preferences, and over time it's being extended to support more options.

You might also check out this alternative: https://github.com/BedeGaming/sinks-rollingfile which I think behaves as you describe.

All the best, 
Nick
