### ISSUE TITLE
Filename without date

### ISSUE THREAD

**Issue by LaurensvandenBerg** [serilog/serilog-sinks-rollingfile#59]
We are creating a small console app which gets started by another process.
we want to add the existing log file, used by this application, as a rolling file sink.
however, if we provide our log file, for instance log20170830110754, it will create a new file with
log20170830110754-20170830.
We can't find the option to turn the datetime appendix off.

**Comment by nblumhardt** [comment]
Hi Laurens,

This scenario isn't supported right now - the `-{Date}` placeholder needs to appear in the filename.

If the parent application is using the log file, however, there will be file sharing issues to consider also - unless the parent app is also using Serilog, the `shared` mode of this sink may not cooperate with the other application, leading to interleaved text.

There are a few options.

 1. If the child process is short-lived, you can just use _Serilog.Sinks.File_ and give it the full filename. Serilog won't roll files over, in this case, but you can get events into a log file with a fixed filename.
 2. If the child process is long-running, and the parent process keeps ownership of it, you can use _Serilog.Sinks.Console_ in the child process and just have the parent process relay events from STDOUT (or STDERR) to the parent's own log file
 3. It's possible to implement a custom sink, perhaps using _Serilog.Sinks.File_ as a base, with whatever rolling logic you choose (non-trivial, but could be based on code from this repo)

Let me know if you need more info or help.

Cheers,
Nick

**Comment by LaurensvandenBerg** [comment]
Hey Nick,

Thanks for the quick response 👍 

Our process is indeed short lived and it will write only a small amount of lines, but we will still go with option 2.
The first option didn't do well with other threads using the same file (as you said, the shared mode doesn't work very well with non-serilog processes).

For now the STDOUT supports our needs :)

Thanks,

Laurens
