### ISSUE TITLE
Can not override formatter

### ISSUE THREAD

**Issue by antonydenyer** [serilog/serilog-sinks-rollingfile#6]
When creating a RollingFile Configuration, is their a good reason why you can not specify ITextFormatter like you use be able to? 

If not I'll create a pull request.

**Comment by nblumhardt** [comment]
Howdy! Nothing's been removed here; I think you're thinking of:

``` csharp
.WriteTo.Sink(new RollingFileSink(..., new JsonFormatter(), ...))
```

However, as luck would have it, I just made exactly the PR you describe over on the File sink and have RollingFile lined up for the same treatment today! :-) https://github.com/serilog/serilog-sinks-file/pull/5

Cheers,
Nick

**Comment by nblumhardt** [comment]
2.1.0 should be up on NuGet in a few short moments: https://ci.appveyor.com/project/serilog/serilog-sinks-rollingfile/build/715

Cheers!

**Comment by antonydenyer** [comment]
You're right I was thinking of that, couldn't do it the RollingFileSink so assumed the new way was to use the extension methods. Got everything working as expected now.

Thanks!
