### ISSUE TITLE
Sink Is Creating New Log Files Within the Day With "_001" at the end

### ISSUE THREAD

**Issue by chic2013** [serilog/serilog-sinks-rollingfile#60]
Hi,
Our project is using Serilog2.3.0, Serilog.Sinks.ColoredConsole 2.0.0, Serilog.Sinks.File 3.1.1, Serilog.Sinks.RollingFile 3.2.0. However, i still see that the log/verbose files created for a day have numbers _001, _002, _003 etc attached next to filename-Date.

The way logger is configured is below:

There is a LoggingConfiguration class that calls to create the SeriLogger

 ```
public static ILogger Setup(ILogProvider logProvider, ConfigurationParameters configuration)
        {
            ILogger logger = logProvider.CreateLogger(configuration);

            logProvider.InternalSetup(logger);

            Log.Logger = logger;

            return logger;
        }
```

There is a class called SerilogProvider below with configuration method below:

```
private readonly LoggerConfiguration _loggerConfiguration;
 public ILogger CreateLogger(ConfigurationParameters configuration)
        {
            if (configuration != null)
            {
                Configure(configuration);
            }

            var logger = _loggerConfiguration.CreateLogger();

            return new SerilogLogger(logger);
        }

 public void InternalSetup(ILogger logger)
        {
            SerilogLibrary.Log.Logger = (logger as SerilogLogger)?.InternalLogger;
        }

private void Configure(ConfigurationParameters configurationParameters)
        {
  _loggerConfiguration
                .WriteTo
                .RollingFile(configurationParameters.ErrorLogFileName, LogEventLevel.Error, LoggingTemplate.Default,
                    retainedFileCountLimit: configurationParameters.ErrorLogRetentionDays);
}
```

This is being consumed as nuget package in the web api. The idea was to create a central logging web api but when i see these different versions of the files, it kind of negates the very purpose I am creating one. Should not different apps logging into this api be able to write into one single log file for a particular date?
Is there something I might be missing?

Thanks

**Comment by nblumhardt** [comment]
@chic2013 are all of the classes involved "singletons" or similar, so that only one logger is ever created?

**Comment by chic2013** [comment]
@nblumhardt my bad, i was registering type for my custom ILogger but in my case it should have been RegisterInsatnce.
Thanks for the prompt response.
