### ISSUE TITLE
On app startup - Doesn't log at all when the existing file size limit has already been reached

### ISSUE THREAD

**Issue by ddprince17** [serilog/serilog-sinks-rollingfile#61]
Steps to reproduce: 
- PathFormat must be by {date}
- Set fileSizeLimitBytes to let say 100000000. 
- Start the app and let it create some logs
- Stop the app
- Open the newly created log file and add text until it weights more than 100MB
- Change the parameter fileSizeLimitBytes to 50000000
- Start the app and let it log... It won't do anything

Expected behavior:
- Since the file size limit had already been reached at the second app start, the sink should automatically create a new file names {date}_001.txt
- The sink should respect all other options as well (like the retainedFileCountLimit)

**Comment by ddprince17** [comment]
Seems like the issue will be fixed soon in the next version of the file sink.

https://github.com/serilog/serilog-sinks-file/pull/35

**Comment by nblumhardt** [comment]
Thanks for getting in touch @DaveWut - https://nblumhardt.com/2017/10/serilog-file-logging/ has some more info in case it helps 👍
