### ISSUE TITLE
Add some guidance about Serilog.Sinks.File vs Serilog.Sinks.RollingFile

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog-sinks-rollingfile#62]
Now that Serilog.Sinks.File has gained more powerful features, I think it would be helpful for users to find some guidance and pointers about whether they should use one Sink or the other in new apps etc ... and also maybe different features supported in each.

Basically the comments that one can find in serilog/serilog-sinks-file#35  :)

**Comment by tsimbalar** [comment]
... or maybe just linking to @nblumhardt 's post is enough ? 
https://nblumhardt.com/2017/10/serilog-file-logging/

**Comment by nblumhardt** [comment]
Done 👍 thanks!
