### ISSUE TITLE
is there possible to separate log  by leg level

### ISSUE THREAD

**Issue by zwbdzb** [serilog/serilog-sinks-rollingfile#63]
{
        "Name": "RollingFile", // 滚动文件
        "Args": { 
          "pathFormat": "logs\\**{level}**\\log-{Date}.txt"
        }
}

is there possible to support  separate log  by leg level

**Comment by skomis-mm** [comment]
@Julian89757 , not via file configuration for now, but try this package
https://github.com/serilog/serilog-sinks-map

**Comment by tsimbalar** [comment]
@Julian89757 Also from now on, for newer projects, it is recommended to use the latest version of the *Serilog.Sinks.File* instead of *Serilog.Sinks.RollingFile*.

See this post for more information : https://nblumhardt.com/2017/10/serilog-file-logging/
