### ISSUE TITLE
Create new File after Reach max file size

### ISSUE THREAD

**Issue by hema2013** [serilog/serilog-sinks-rollingfile#65]
Hello,
  I have set max files size :500 MB .  if the file reached to this size , there is no log added . So Is there a bility to create another file ?

 Thanks

**Comment by nblumhardt** [comment]
Hi! You will need to modify your code slightly to use _Serilog.Sinks.File_ instead, with the `RollingInterval.Day` option and `rollOnFileSizeLimit: true`.

More details in this post: https://nblumhardt.com/2017/10/serilog-file-logging/

Best regards,
Nick
