### ISSUE TITLE
Is it possible to vary how/where the date is placed in the file name....

### ISSUE THREAD

**Issue by natiki** [serilog/serilog-sinks-rollingfile#66]
Hi,

By default we end up with:

> log20180521.txt

Is it possible to vary that to say:

> 2018-05-21_log.txt

reason being we output all our logs to a common location with that format so adding one in via the rolling provider means it is not grouped together with the others.

**Comment by nblumhardt** [comment]
Hi! Using `"{Date}_log.txt"` works and would come close here.

Format specifiers aren't accepted in the `{Date}` token, though. It's not likely we'll add this additional functionality in the near future, but a proposal for implementation would be welcome if anyone is interested in setting the scenes for a PR. Thanks!
