### ISSUE TITLE
PathFormat is not threaded platform independent

### ISSUE THREAD

**Issue by lehmamic** [serilog/serilog-sinks-rollingfile#67]
If following path is configured in the app settings.json "pathFormat": ".\\log\\applog-{Date}.log", which contains windows path notation, no log files get created when running it on linux or mac.

**Comment by hmiguel** [comment]
Same issue here, I want to save my log files in "var/log/" folder, but Serilog always create a new file with the name specified in pathFormat (slashes included).

I have my configuration like this

`` "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "RollingFile",
              "Args": { "pathFormat": "\\var\\log\\myApp\\log-{Date}.log" }
            }
          ]
        }
      }``

**Comment by nblumhardt** [comment]
Hi, and thanks for the note! That's by design - you'll need to use different configurations across Linux/macOS.
