### ISSUE TITLE
Padding format specifier does not seem to function

### ISSUE THREAD

**Issue by gautelo** [serilog/serilog-sinks-rollingfile#71]
Consider log output for a thread of ID, say, 15 when including the WithThreadId enricher and `{ThreadId,5}` in the ouputTemplate. The Console sink outputs the thread ID nicely pre padded to a total length of 5 ("&nbsp;&nbsp;&nbsp;15"), but in the RollingFile sink outputs the thread ID and then 5 spaces ("15&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;").

I would like them both to behave the same; the way the Console does it, which conforms to the .net formatting specifiers.

**Comment by nblumhardt** [comment]
Thanks! Will have a look :+1:

**Comment by nblumhardt** [comment]
Created https://github.com/serilog/serilog/pull/1233
