### ISSUE TITLE
Create multiple log files using Serilog

### ISSUE THREAD

**Issue by ranjithjains** [serilog/serilog-sinks-rollingfile#72]
I would like to know if we can log to multiple files in Serilog.
For example, i would like to create logs of TYPE1 to one file and TYPE2 to another file.

**Comment by ranjithjains** [comment]
Hi @nblumhardt any help with this.

**Comment by ranjithjains** [comment]
@nblumhardt i have created an application with logging functionality using Serilog. I would like to create two log files. One log file for application startup and the other file for other functionality of the application.

**Comment by tsimbalar** [comment]
Hi @ranjithjains ,

take a look at [*Serilog.Sinks.Map*](https://github.com/serilog/serilog-sinks-map) , the README more or less covers that scenario.

**Comment by ranjithjains** [comment]
Hi @nblumhardt any help with this.

**Comment by nblumhardt** [comment]
It's also possible just to create two separate `Logger`s via separate `LoggerConfiguration`s and use them independently. Closing as this is a stale ticket now, but please let us know if you need more details @ranjithjains .

**Comment by Maru9961** [comment]
any solution yet?

**Comment by cocowalla** [comment]
@Maru9961 there are 2 solutions, both already mentioned here in this thread.

1. Create a sink for each type:

```csharp
Log.Logger = new LoggerConfiguration()
	.WriteTo.Logger(x =>
	{
		x.WriteTo.File("event_type_1.txt");
		x.Filter.ByIncludingOnly(e => e.Properties["event_type"] == "type_1");
	})
	.WriteTo.Logger(x =>
	{
		x.WriteTo.File("event_type_1.txt");
		x.Filter.ByIncludingOnly(e => e.Properties["event_type"] == "type_2");
	})
	.CreateLogger();
```

2. Use [Serilog.Sinks.Map](https://github.com/serilog/serilog-sinks-map), which does the same but with nicer config syntax:

```csharp
Log.Logger = new LoggerConfiguration()
	.WriteTo.Map("event_type", "type_1", (name, wt) => wt.File("event_type_1.txt"))
	.WriteTo.Map("event_type", "type_2", (name, wt) => wt.File("event_type_2.txt"))
	.CreateLogger();
```

**Comment by frankmehlhop** [comment]
@cocowalla Thank you for your code above! 
I wonder **how can I use the two different types** (1 and 2) in code also on the run?
I think of some thing like "__logger.Log<type_2>("...");"?

**Comment by cocowalla** [comment]
@frankmehlhop I think you are asking how to log as `event_type` 1 and 2 at runtime? This is done using [logging context](https://nblumhardt.com/2016/08/context-and-correlation-structured-logging-concepts-in-net-5/).

As per the docs, there are multiple ways to do this:

1. Create a logger just for such events:
```c#
var eventType1Logger = Log.ForContext("event_type", "type_1");
```
2. Use an ambient/temporary log context
```c#
using (LogContext.PushProperty("event_type", "type_1"))
{
    // Process request; all logged events will carry `event_type`
    Log.Information("This log message will have an event_type property");
}
```
You can do this for individual logs, or with an extensibility point in whatever framework you are using. For example, if you are using ASP.NET Core, you could use middleware:

```c#
public async Task Invoke(HttpContext context)
{
    if (!some_check_to_add_event_type_1)
        return;

    using (LogContext.PushProperty("event_type", "type_1"))
    {
        await this.next.Invoke(context);
    }
}
```

3. You can use globally attached properties:
```c#
Log.Logger = new LoggerConfiguration()
    .Enrich.WithProperty("event_type ", "type_1")
    .Enrich.WithProperty("Environment", ConfigurationManager.AppSettings["Environment"])
    // Other logger configuration
```
4. You can use an `ILogEventEnricher` to programmatically enrich logs

For (3), if you want to attach the `event_type` on a log-by-log basis, you can make it nicer with an extension method:
```c#
public static class LogExtensions
{
    public static ILogger AsEventType1(this ILogger log)
        => log.ForContext("event_type", "type_1");
}
...
Log.AsEventType1().Error("Something happened!");
```

**Comment by frankmehlhop** [comment]
Thank you!
