### ISSUE TITLE
Improve documentation of fileSizeLimitBytes

### ISSUE THREAD

**Issue by bladeoflight16** [serilog/serilog-sinks-rollingfile#73]
The README helpfully mentions the `fileSizeLimitBytes` parameter, which notifies us of default a maximum size on log files and allows us to configure it.

However, it's not clear what happens when the maximum is reached. Does Serilog rename the file that exceeds the limit? Does it delete it and create a new one? Does it create a new log with a different name? I don't see any need for elaborate details here, but a quick note would be helpful. E.g., if it depends on another parameter or is otherwise complex, just note the default and where all the gory details can be found.

The parameter's documentation comment is similarly unclear about the behavior.

This information is important because it will help users determine whether I need to alter the default or not. For example, if it gets deleted, I would probably disable it. If not, I would leave it alone.

---

Just wanna say thanks for this library. I like it much better than most other logging technologies I've seen/used. It's so much simpler.

**Comment by nblumhardt** [comment]
Thanks for this! Sorry it took a while to reply, there was a bit much traffic to keep up with, on this repository, so I tuned out for a time :-)

I've made a small improvement to: https://github.com/serilog/serilog-sinks-file/blob/dev/README.md#limits - going forward I think we'll be recommending the `File` sink more strongly in preference to `RollingFile`.

**Comment by bladeoflight16** [comment]
@nblumhardt I hadn't realize rolling had been integrated into that sink. Thanks!

**Comment by micktion** [comment]
I have to say as someone who has used Log4net 4ever... I wouldn't expect the file sink to simply stop logging when it hits the configured file size limit.  I can't think of why anyone would want that? i.e. just don't log anything after some limit.

I would expect it to roll the log into a new file.
