### ISSUE TITLE
Sink is not creating Logger file on .Net Core

### ISSUE THREAD

**Issue by sonisudarshan0** [serilog/serilog-sinks-rollingfile#75]
When i tried to create logger using following code:

` var log = new LoggerConfiguration()
            .WriteTo.RollingFile("D:\\TM3171-TSRCoreModulesAnalysisDesign\\trunk\\B. Source Code\\Dapper-Postgres-Migrate-Test\\WEBAPI.Database\\ReadMe\\Date_Logs_2019-06-05.txt")
            .CreateLogger();
            log.Information(error);`

Installed package  `Serilog.Sinks.RollingFile`

![logger_errror](https://user-images.githubusercontent.com/50704950/58944566-bce22d80-879f-11e9-87d0-51d6ba8e8254.png)

this code its not able to create any logger/Log file into my project

**Comment by cocowalla** [comment]
Most likely issue is that the parent directory doesn't exist, or the application in question doesn't have permission to write to it.

Otherwise, the first thing to try is enabling Serilog's internal [diagnostic logging](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics) - this will print to the console for some kinds of problems creating sinks.

**Comment by SimonCropp** [comment]
from the readme 

> Important note: the rolling functionality in this sink has been improved and merged into the Serilog.Sinks.File package. RollingFile will be maintained for the foreseeable future, however File is recommended for new applications.

So perhaps try Serilog.Sinks.File

@nblumhardt perhaps close this one? and add "this project is deprecated in the issue + pr templates?

**Comment by nblumhardt** [comment]
Thanks for the note @SimonCropp; we haven't gone as far as calling `RollingFile` deprecated, so far, since it's used by a lot of projects and we'll still review and merge fixes, here. (Open to other ideas, though.)

Closing this as it's stale, and unlikely to be a sink bug 👍
