### ISSUE TITLE
Enable specifiers for the directories

### ISSUE THREAD

**Issue by lexdevel** [serilog/serilog-sinks-rollingfile#76]
Hello,

I see that it's [forbidden to use specifiers as the part of the directory name](https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/src/Serilog.Sinks.RollingFile/Sinks/RollingFile/TemplatedPathRoller.cs#L48). I wonder if there's a chance you could allow to use at least `Date` specifier? Or is there any other ways to log to *date* folders?

Thank you in advance

**Comment by cocowalla** [comment]
While this sink is still being maintained, rolling file functionality was merged into the much more actively maintained [serilog-sinks-file](https://github.com/serilog/serilog-sinks-file) some time ago - that is considered the "main" file sink now.

You might want to consider opening an issue at `serilog-sinks-file` instead, as new features are far more likely to be added there than here.

**Comment by lexdevel** [comment]
Thanks, will try.
