### ISSUE TITLE
deprecate this nuget

### ISSUE THREAD

**Issue by SimonCropp** [serilog/serilog-sinks-rollingfile#77]
https://devblogs.microsoft.com/nuget/deprecating-packages-on-nuget-org/

**Comment by nblumhardt** [comment]
I think this is worth strong consideration 👍

**Comment by SimonCropp** [comment]
need any help from me?

**Comment by nblumhardt** [comment]
Thanks for the nudge, @SimonCropp 🙏 

![image](https://user-images.githubusercontent.com/342712/94398469-eef37c00-01a8-11eb-8dab-09240b1c9888.png)

**Comment by nblumhardt** [comment]
I think there's still an opportunity to deprecate/archive packages in the Serilog org; here are a few candidates I can find in a quick scan, sure there are more:

 * https://github.com/serilog/serilog-sinks-literate
 * https://github.com/serilog/serilog-sinks-coloredconsole
 * https://github.com/serilog/serilog-settings-combined
 
There are also a lot that are outdated and have no maintainers that I think we could add to this list, but needs more digging around :-)
